// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Prasoft.Data
{
    public partial class OrderLine
    {
        public long Id { get; set; }
        public long ProductVariantGroupId { get; set; }
        public long OrderId { get; set; }
        public long ProductId { get; set; }
        public long Quantity { get; set; }
        public double UnitPrice { get; set; }
        public double DiscountRate { get; set; }

        public virtual Orders Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductVariantGroup ProductVariantGroup { get; set; }
    }
}