// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Prasoft.Data
{
    public partial class Orders
    {
        public Orders()
        {
            OrderLine = new HashSet<OrderLine>();
        }

        public long Id { get; set; }
        public string OrderDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string CustomerMailAddress { get; set; }
        public string CustomerTaxAdministration { get; set; }
        public long CustomerTaxId { get; set; }

        public virtual ICollection<OrderLine> OrderLine { get; set; }
    }
}