// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Prasoft.Data
{
    public partial class Picture
    {
        public Picture()
        {
            VariantPicture = new HashSet<VariantPicture>();
        }

        public long Id { get; set; }
        public long ProductId { get; set; }
        public string Picture1 { get; set; }

        public virtual Product Product { get; set; }
        public virtual ICollection<VariantPicture> VariantPicture { get; set; }
    }
}