// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Prasoft.Data
{
    public partial class ProductVariantGroup
    {
        public ProductVariantGroup()
        {
            OrderLine = new HashSet<OrderLine>();
            ProductVariant = new HashSet<ProductVariant>();
            VariantPicture = new HashSet<VariantPicture>();
        }

        public long Id { get; set; }
        public long? ProductId { get; set; }
        public double? Price { get; set; }
        public string Barcode { get; set; }
        public long? Stock { get; set; }

        public virtual Product Product { get; set; }
        public virtual ICollection<OrderLine> OrderLine { get; set; }
        public virtual ICollection<ProductVariant> ProductVariant { get; set; }
        public virtual ICollection<VariantPicture> VariantPicture { get; set; }
    }
}