// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Prasoft.Data
{
    public partial class Product
    {
        public Product()
        {
            OrderLine = new HashSet<OrderLine>();
            Picture = new HashSet<Picture>();
            ProductVariantGroup = new HashSet<ProductVariantGroup>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Barcode { get; set; }
        public long Stock { get; set; }
        public double Price { get; set; }
        public long? CategoryId { get; set; }

        public virtual Categories Category { get; set; }
        public virtual ICollection<OrderLine> OrderLine { get; set; }
        public virtual ICollection<Picture> Picture { get; set; }
        public virtual ICollection<ProductVariantGroup> ProductVariantGroup { get; set; }
    }
}