// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Prasoft.Data
{
    public partial class VariantValue
    {
        public VariantValue()
        {
            ProductVariant = new HashSet<ProductVariant>();
        }

        public long Id { get; set; }
        public string Value { get; set; }
        public long VariantNameId { get; set; }

        public virtual VariantName VariantName { get; set; }
        public virtual ICollection<ProductVariant> ProductVariant { get; set; }
    }
}