// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Prasoft.Data
{
    public partial class VariantPicture
    {
        public long Id { get; set; }
        public long PictureId { get; set; }
        public long ProductVariantGroupId { get; set; }

        public virtual Picture Picture { get; set; }
        public virtual ProductVariantGroup ProductVariantGroup { get; set; }
    }
}